export const users=[
    {
        id:1,
        name:"Misbahul",
        bio:"Absolutely Improvment",
        books:[
            {
                id:1,
                title:"buku1"
            },
            {
                id:2,
                title:"buku2"
            },
            {
                id:3,
                title:"buku3"
            },
            {
                id:4,
                title:"buku4"
            },
        ]
    },
    {
        id:2,
        name:"Muttaqin",
        bio:"Learn Faster",
        books:[
            {
                id:1,
                title:"buku1"
            },
            {
                id:2,
                title:"buku2"
            },
            {
                id:3,
                title:"buku3"
            },
            {
                id:4,
                title:"buku4"
            },
        ]
    },
    {
        id:3,
        name:"Misbahul",
        bio:"Quit it",
        books:[
            {
                id:1,
                title:"buku1"
            },
            {
                id:2,
                title:"buku2"
            },
            {
                id:3,
                title:"buku3"
            },
            {
                id:4,
                title:"buku4"
            },
        ]
    },
]